if (compile_threaded)
  string(APPEND CFLAGS   " -fopenmp")
  string(APPEND FFLAGS   " -fopenmp")
  string(APPEND CXXFLAGS " -fopenmp")
  string(APPEND LDFLAGS  " -fopenmp")
endif()
if (NOT DEBUG)
  string(APPEND CFLAGS   " -O2")
  string(APPEND FFLAGS   " -O2")
  string(APPEND CXXFLAGS " -O2")
endif()
if (DEBUG)
  string(APPEND FFLAGS   " -g -Wall -fbacktrace -fcheck=bounds -ffpe-trap=zero,overflow")
  string(APPEND CFLAGS   " -O0 -g")
  string(APPEND CXXFLAGS " -O0 -g")
endif()
string(APPEND CFLAGS   " -fp-model precise -std=gnu99")
string(APPEND CXXFLAGS " -fp-model precise")
string(APPEND FFLAGS   " -fconvert=big-endian -ffree-line-length-none -ffixed-line-length-none -fallow-argument-mismatch")
set(SUPPORTS_CXX "TRUE")
string(APPEND CPPDEFS " -DFORTRANUNDERSCORE -DNO_R16 -DCPRGNU -DHAVE_SLASHPROC -DHIDE_MPI")
string(APPEND FC_AUTO_R8 " -fdefault-real-8")
string(APPEND FFLAGS_NOOPT " -O0")
string(APPEND FIXEDFLAGS " -ffixed-form")
string(APPEND FREEFLAGS " -ffree-form")
set(HAS_F2008_CONTIGUOUS "FALSE")
set(MPIFC "mpigfortran")
set(MPICC "mpiicx")
set(MPICXX "mpiicpx")
set(SCC "icx")
set(SCXX "icpx")
set(SFC "gfortran")

set(CXX_LINKER "CXX")
string(APPEND SLIBS " -lmkl_intel_lp64 -lmkl_sequential -lmkl_core")
#string(APPEND SLIBS " -fiopenmp -fopenmp-targets=spir64")
set(USE_SYCL "TRUE")
string(APPEND KOKKOS_OPTIONS " -DCMAKE_CXX_STANDARD=17 -DKokkos_ENABLE_SERIAL=On -DKokkos_ARCH_INTEL_PVC=On -DKokkos_ENABLE_SYCL=On -DKokkos_ENABLE_EXPLICIT_INSTANTIATION=Off")
string(APPEND SYCL_FLAGS " -\-intel -fsycl -fsycl-targets=spir64_gen -mlong-double-64 -Xsycl-target-backend \"-device pvc\"")
#string(APPEND SYCL_FLAGS " -fsycl -mlong-double-64")
#string(APPEND CXX_LDFLAGS " -Wl,-\-defsym,main=MAIN_\_ -lifcore -\-intel -fsycl -lsycl -mlong-double-64 -Xsycl-target-backend \"-device 12.60.7\"")
#string(APPEND CXX_LDFLAGS " -Wl,-\-defsym,main=MAIN_\_ -lgfortran -fsycl -lsycl -mlong-double-64 -Xsycl-target-backend \"-device 12.60.7\"")
string(APPEND CXX_LDFLAGS " -fsycl -lsycl -mlong-double-64 -Xsycl-target-backend \"-device pvc\"")
#string(APPEND CXX_LDFLAGS " -fsycl -lsycl -mlong-double-64")
