if (compile_threaded)
	string(APPEND CMAKE_C_FLAGS   " -qopenmp")
  string(APPEND CMAKE_Fortran_FLAGS   " -fopenmp")
  string(APPEND CMAKE_CXX_FLAGS " -qopenmp")
  string(APPEND CMAKE_EXE_LINKER_FLAGS  " -fopenmp")
endif()
if (NOT DEBUG)
  string(APPEND CMAKE_C_FLAGS_RELEASE   " -O2")
  string(APPEND CMAKE_FORTRAN_FLAGS_RELEASE   " -O2")
  string(APPEND CMAKE_CXX_FLAGS_RELEASE " -O2")
endif()
if (DEBUG)
	string(APPEND CMAKE_FORTRAN_FLAGS_DEBUG   " -O0 -g -check uninit -check bounds -check pointers -fpe0 -check noarg_temp_created")
	string(APPEND CMAKE_C_FLAGS_DEBUG   " -O0 -g")
  string(APPEND CMAKE_CXX_FLAGS_DEBUG " -O0 -g")
endif()
string(APPEND CMAKE_C_FLAGS   " -fp-model precise -std=gnu99")
string(APPEND CMAKE_CXX_FLAGS " -fp-model precise")
string(APPEND CMAKE_Fortran_FLAGS " -fconvert=big-endian -ffree-line-length-none -ffixed-line-length-none -fallow-argument-mismatch")
set(SUPPORTS_CXX "TRUE")
string(APPEND CPPDEFS " -DFORTRANUNDERSCORE -DNO_R16  -DCPRGNU -DHAVE_SLASHPROC -DHIDE_MPI")
#string(APPEND FC_AUTO_R8 " -fdefault-real-8")
#string(APPEND FFLAGS_NOOPT " -O0")
string(APPEND  CMAKE_Fortran_FORMAT_FIXED_FLAG" -ffixed-form")
string(APPEND CMAKE_Fortran_FORMAT_FREE_FLAG " -ffree-form")
set(HAS_F2008_CONTIGUOUS "FALSE")

set(CXX_LINKER "CXX")

set(MPIFC "/home/omarahmed/bin/mpigfortran")
set(MPICC "/home/omarahmed/bin/mpiicx")
set(MPICXX "/home/omarahmed/bin/mpiicpx")
set(SCC "icx")
set(SCXX "icpx")
set(SFC "gfortran")
#string(APPEND CMAKE_EXE_LINKER_FLAGS " -fiopenmp -fopenmp-targets=spir64")
set(USE_SYCL "TRUE")
string(APPEND SYCL_FLAGS " -\-intel -fsycl -fsycl-targets=spir64_gen -Xsycl-target-backend \"-device 12.60.7\"")
