if (compile_threaded)
  string(APPEND CFLAGS   " -qopenmp")
  string(APPEND FFLAGS   " -qopenmp")
  string(APPEND CXXFLAGS " -qopenmp")
  string(APPEND LDFLAGS  " -qopenmp")
endif()
if (NOT DEBUG)
  string(APPEND CFLAGS   " -O2")
  string(APPEND FFLAGS   " -O2")
  string(APPEND CXXFLAGS " -O2")
endif()
if (DEBUG)
  string(APPEND FFLAGS   " -O0 -g -check uninit -check bounds -check pointers -fpe0 -check noarg_temp_created")
  string(APPEND CFLAGS   " -O0 -g")
  string(APPEND CXXFLAGS " -O0 -g")
endif()
string(APPEND CFLAGS   " -fp-model precise -std=gnu99")
string(APPEND CXXFLAGS " -fp-model precise")
string(APPEND FFLAGS   " -convert big_endian -assume byterecl -assume realloc_lhs -fp-model precise")
set(SUPPORTS_CXX "TRUE")
string(APPEND CPPDEFS " -DFORTRANUNDERSCORE -DNO_R16 -DCPRINTEL -DHAVE_SLASHPROC -DHIDE_MPI")
string(APPEND FC_AUTO_R8 " -r8")
string(APPEND FFLAGS_NOOPT " -O0")
string(APPEND FIXEDFLAGS " -fixed -132")
string(APPEND FREEFLAGS " -free")
set(HAS_F2008_CONTIGUOUS "TRUE")
set(MPIFC "mpiifx")
set(MPICC "mpiicx")
set(MPICXX "mpiicpx")
set(SCC "icx")
set(SCXX "icpx")
set(SFC "ifx")

set(CXX_LINKER "CXX")
string(APPEND SLIBS " -lmkl_intel_lp64 -lmkl_sequential -lmkl_core")
string(APPEND SLIBS " -fiopenmp -fopenmp-targets=spir64")
set(USE_SYCL "TRUE")
string(APPEND KOKKOS_OPTIONS " -DCMAKE_CXX_STANDARD=17 -DKokkos_ENABLE_OPENMP=ON -DKokkos_ARCH_INTEL_PVC=ON -DKokkos_ENABLE_SYCL=ON -DKokkos_ENABLE_EXPLICIT_INSTANTIATION=Off")
#string(APPEND SYCL_FLAGS " -\-intel -fsycl -fsycl-targets=spir64_gen -mlong-double-64 -Xsycl-target-backend \"-device pvc\"")
string(APPEND SYCL_FLAGS " -\-intel -fsycl -mlong-double-64")
#string(APPEND CXX_LDFLAGS " -Wl,-\-defsym,main=MAIN_\_ -lifcore -\-intel -fsycl -lsycl -mlong-double-64 -Xsycl-target-backend \"-device pvc\"")
string(APPEND CXX_LDFLAGS " -Wl,-\-defsym,main=MAIN_\_ -lifcore -\-intel -fsycl -lsycl -mlong-double-64")
